In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df = pd.read_csv('train.txt',sep = ';', header= None, names = ['text', 'emotions'])

In [22]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [23]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [24]:
unique_emotions = df['emotions'].unique()
emotions_num = {}

Numbering all emotions

In [25]:
i = 0 
for emo in unique_emotions :
    emotions_num[emo] = i
    i+= 1

df['emotions'] = df['emotions'].map(emotions_num)

In [26]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

Convert everything in lower case

In [27]:
df['text'] = df['text'].apply(lambda x : x.lower())

Remove Punctuations

In [28]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('', '',string.punctuation))

In [29]:
df['text'] = df['text'].apply(remove_punc)

remove digits

In [31]:
def remove_digit(txt):
    new = ''
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_digit)

Remove URLs/ Link

In [32]:
df['text'] = df['text'].str.replace(r'http\S+|www\S+', '', regex=True)

remove html tags

In [33]:
df['text'] = df['text'].str.replace(r'<.*?>', '', regex=True)

remove emojis & special char

In [34]:
def remove_emoji(txt):
    new = ''
    for i in txt:
        if i.isascii():
            new += i
        return new

df['text'] = df['text'].apply(remove_emoji)

remove stop words

In [37]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [38]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [47]:
stopwords = stopwords.words('english')

In [48]:
def remove(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if not i in stopwords:
            cleaned.append(i)

    return ' '.join(cleaned)

In [49]:
df.loc[1]['text']

'i'