In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('train.txt',sep = ';', header= None, names = ['text', 'emotions'])

In [6]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [7]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [10]:
unique_emotions = df['emotions'].unique()
emotions_num = {}

Numbering all emotions

In [11]:
i = 0 
for emo in unique_emotions :
    emotions_num[emo] = i
    i+= 1

df['emotions'] = df['emotions'].map(emotions_num)

In [12]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]